services:
  db:
    image: postgres:16-alpine
    container_name: chatai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatai
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chatai_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      # App config
      CONFIG_JSON_PATH: /app/config.local.json
      # DB
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/chatai
      # Redis optional (not part of this compose)
      # REDIS_URL: redis://redis:6379/0
      # LLM settings (placeholders)
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-test}
      LLM_MODEL: ${LLM_MODEL:-gemini-2.5-flash}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-test}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
