"""add_channel_id_to_conversation_traces

Revision ID: 346d29e0c1be
Revises: a5c8010a73bf
Create Date: 2025-08-31 16:58:05.987924

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "346d29e0c1be"
down_revision: str | Sequence[str] | None = "a5c8010a73bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_conversation_traces", sa.Column("channel_id", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_conversation_traces", "channel_id")
    # ### end Alembic commands ###
