"""Add timing configuration to tenant_project_configs

Revision ID: 628074c68476
Revises: 190180b9a510
Create Date: 2025-09-15 13:51:08.481655

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "628074c68476"
down_revision: str | Sequence[str] | None = "190180b9a510"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add timing configuration columns to tenant_project_configs."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant_project_configs",
        sa.Column(
            "wait_time_before_replying_ms", sa.Integer(), nullable=False, server_default="2000"
        ),
    )
    op.add_column(
        "tenant_project_configs",
        sa.Column("typing_indicator_enabled", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.add_column(
        "tenant_project_configs",
        sa.Column("min_typing_duration_ms", sa.Integer(), nullable=False, server_default="1000"),
    )
    op.add_column(
        "tenant_project_configs",
        sa.Column("max_typing_duration_ms", sa.Integer(), nullable=False, server_default="5000"),
    )
    op.add_column(
        "tenant_project_configs",
        sa.Column("message_reset_enabled", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.add_column(
        "tenant_project_configs",
        sa.Column("natural_delays_enabled", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.add_column(
        "tenant_project_configs",
        sa.Column("delay_variance_percent", sa.Integer(), nullable=False, server_default="20"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove timing configuration columns from tenant_project_configs."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_project_configs", "delay_variance_percent")
    op.drop_column("tenant_project_configs", "natural_delays_enabled")
    op.drop_column("tenant_project_configs", "message_reset_enabled")
    op.drop_column("tenant_project_configs", "max_typing_duration_ms")
    op.drop_column("tenant_project_configs", "min_typing_duration_ms")
    op.drop_column("tenant_project_configs", "typing_indicator_enabled")
    op.drop_column("tenant_project_configs", "wait_time_before_replying_ms")
    # ### end Alembic commands ###
