"""Add HandoffRequest table for tracking human handoff requests

Revision ID: 8405d74fc303
Revises: 0ceb635e0117
Create Date: 2025-09-10 18:33:01.488344

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8405d74fc303"
down_revision: str | Sequence[str] | None = "0ceb635e0117"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_channel_instances_tenant_id_active"), table_name="channel_instances", postgresql_where="(deleted_at IS NULL)")
    op.drop_index(op.f("ix_flows_tenant_id_active"), table_name="flows", postgresql_where="(deleted_at IS NULL)")
    op.drop_index(op.f("ix_tenants_deleted_at_id"), table_name="tenants")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_tenants_deleted_at_id"), "tenants", ["deleted_at", "id"], unique=False)
    op.create_index(op.f("ix_flows_tenant_id_active"), "flows", ["tenant_id"], unique=False, postgresql_where="(deleted_at IS NULL)")
    op.create_index(op.f("ix_channel_instances_tenant_id_active"), "channel_instances", ["tenant_id"], unique=False, postgresql_where="(deleted_at IS NULL)")
    # ### end Alembic commands ###
