"""Add agent thought tracing tables

Revision ID: a5c8010a73bf
Revises: add_training_mode
Create Date: 2025-08-31 06:44:49.794137

"""
import os

# Import the EncryptedString type
import sys
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))
from app.db.types import EncryptedString

# revision identifiers, used by Alembic.
revision: str = "a5c8010a73bf"
down_revision: str | Sequence[str] | None = "add_training_mode"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("agent_conversation_traces",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("tenant_id", sa.UUID(), nullable=False),
    sa.Column("user_id", EncryptedString(), nullable=False),
    sa.Column("session_id", sa.String(length=255), nullable=True),
    sa.Column("agent_type", sa.String(length=100), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("total_thoughts", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("tenant_id", "user_id", "agent_type", name="uq_trace_per_user_agent")
    )
    op.create_index("ix_trace_last_activity", "agent_conversation_traces", ["last_activity_at"], unique=False)
    op.create_index("ix_trace_tenant_user", "agent_conversation_traces", ["tenant_id", "user_id"], unique=False)
    op.create_table("agent_thoughts",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("conversation_trace_id", sa.UUID(), nullable=False),
    sa.Column("user_message", EncryptedString(), nullable=False),
    sa.Column("current_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("available_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("reasoning", sa.Text(), nullable=False),
    sa.Column("selected_tool", sa.String(length=100), nullable=False),
    sa.Column("tool_args", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("confidence", sa.Float(), nullable=True),
    sa.Column("tool_result", sa.Text(), nullable=True),
    sa.Column("agent_response", EncryptedString(), nullable=True),
    sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("processing_time_ms", sa.Integer(), nullable=True),
    sa.Column("model_name", sa.String(length=100), nullable=False),
    sa.Column("extra_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["conversation_trace_id"], ["agent_conversation_traces.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("ix_thought_tool_name", "agent_thoughts", ["selected_tool"], unique=False)
    op.create_index("ix_thought_trace_timestamp", "agent_thoughts", ["conversation_trace_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_thought_trace_timestamp", table_name="agent_thoughts")
    op.drop_index("ix_thought_tool_name", table_name="agent_thoughts")
    op.drop_table("agent_thoughts")
    op.drop_index("ix_trace_tenant_user", table_name="agent_conversation_traces")
    op.drop_index("ix_trace_last_activity", table_name="agent_conversation_traces")
    op.drop_table("agent_conversation_traces")
    # ### end Alembic commands ###
