"""add admin phone numbers remove training mode fields

Revision ID: f4db6466c728
Revises: 346d29e0c1be
Create Date: 2025-08-31 19:56:01.086156

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4db6466c728"
down_revision: str | Sequence[str] | None = "346d29e0c1be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_chat_threads_training_flow"), "chat_threads", type_="foreignkey")
    op.drop_column("chat_threads", "training_mode")
    op.drop_column("chat_threads", "training_flow_id")
    op.drop_column("chat_threads", "training_mode_since")
    op.drop_column("flows", "training_password")
    op.add_column("tenants", sa.Column("admin_phone_numbers", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "admin_phone_numbers")
    op.add_column("flows", sa.Column("training_password", postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column("chat_threads", sa.Column("training_mode_since", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column("chat_threads", sa.Column("training_flow_id", sa.UUID(), autoincrement=False, nullable=True))
    op.add_column("chat_threads", sa.Column("training_mode", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f("fk_chat_threads_training_flow"), "chat_threads", "flows", ["training_flow_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###
